-- =============================================================================
-- Jetson Thor Pinmux – PostgreSQL Schema
-- Generated by extract_xlsm.py
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- pins
--   Static reference data for every MPIO pad on the Thor SoC.
--   Populated once from the XLSM template; never modified at runtime.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pins (
    id                   SERIAL PRIMARY KEY,
    row_number           INTEGER      NOT NULL,  -- original Excel row (debugging)
    sort_order           INTEGER      NOT NULL,

    -- Physical identity
    connector_pin        VARCHAR(20),             -- e.g. "L60"  (module connector ball)
    signal_name          VARCHAR(100),            -- e.g. "SYS_RESET_N"
    ball_name            VARCHAR(50)  NOT NULL,   -- MPIO name, e.g. "SF_RST_N"
    verilog_name         VARCHAR(100),            -- Verilog signal name
    ball_location        VARCHAR(20),             -- physical SoC ball, e.g. "K55"

    -- Mux options (dropdown choices for customer_usage)
    mux_unused           VARCHAR(100),
    mux_gpio             VARCHAR(100),
    mux_sfio0            VARCHAR(100),
    mux_sfio1            VARCHAR(100),
    mux_sfio2            VARCHAR(100),
    mux_sfio3            VARCHAR(100),

    -- Allowed pin directions per mux option  (I=Input, O=Output, B=Bidirectional)
    allowed_dir_gpio     VARCHAR(5),
    allowed_dir_sfio0    VARCHAR(5),
    allowed_dir_sfio1    VARCHAR(5),
    allowed_dir_sfio2    VARCHAR(5),
    allowed_dir_sfio3    VARCHAR(5),

    -- Pin group functions
    func_f0              VARCHAR(100),
    func_f1              VARCHAR(100),
    func_f2              VARCHAR(100),
    func_f3              VARCHAR(100),
    func_safe            VARCHAR(100),

    -- General pad information
    dt_pin_name          VARCHAR(100),            -- Linux device-tree pin name
    power_rail           VARCHAR(100),
    wake_source          VARCHAR(50),             -- e.g. "wake0"
    strap                VARCHAR(50),
    gte                  VARCHAR(100),
    dpd_control          VARCHAR(100),
    dpd_group            VARCHAR(100),
    pad_category         VARCHAR(50),
    pad_type             VARCHAR(200),
    pull_strength        VARCHAR(20),
    por_state            VARCHAR(20),             -- Power-On Reset state
    io_block_voltage     VARCHAR(20),
    sdmmc_dat_cmd        VARCHAR(50),
    net_name             VARCHAR(200),
    devkit_usage         VARCHAR(200),
    gpio_true_direction  VARCHAR(20),
    comment              TEXT,

    -- Power-On Reset / hardware default configuration
    default_pin_group    VARCHAR(100),
    default_pupd         VARCHAR(20),             -- NORMAL / PULL_UP / PULL_DOWN
    default_tristate     VARCHAR(20),             -- NORMAL / TRISTATE
    default_e_input      VARCHAR(20),             -- ENABLE / DISABLE
    default_gpio_init    VARCHAR(10),             -- N/A / 0 / 1

    -- DevKit template defaults (pre-filled "Filled in by Customers" values)
    -- These seed new configurations so users start from the DevKit baseline.
    tmpl_customer_usage  VARCHAR(100),
    tmpl_pin_direction   VARCHAR(30),
    tmpl_initial_state   VARCHAR(30),
    tmpl_wake_pin        VARCHAR(10),
    tmpl_lock            VARCHAR(10),
    tmpl_e_io_od         VARCHAR(10),
    tmpl_drv_type        VARCHAR(10),
    tmpl_e_lpbk          VARCHAR(10),
    tmpl_e_18v           VARCHAR(10),
    tmpl_schmitt         VARCHAR(20),
    tmpl_e_hsrx18v       VARCHAR(10),
    tmpl_int_pull_up     VARCHAR(20),
    tmpl_int_pull_down   VARCHAR(20),
    tmpl_ext_pull_up     VARCHAR(20),
    tmpl_ext_pull_down   VARCHAR(20),
    tmpl_deep_sleep_state VARCHAR(30),

    -- Whether this pin can be reconfigured by a customer
    -- (FALSE for oscillator/special-function pads outside the config range)
    is_configurable      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS pins_ball_name_idx ON pins(ball_name);
CREATE INDEX        IF NOT EXISTS pins_sort_order_idx ON pins(sort_order);

-- ---------------------------------------------------------------------------
-- pad_voltage_rails
--   Reference list of pad voltage rails and their supported voltages.
--   The DevKit default voltage is stored here; per-configuration overrides
--   live in pad_voltage_configs.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pad_voltage_rails (
    id              SERIAL PRIMARY KEY,
    voltage_rail    VARCHAR(50)  NOT NULL UNIQUE,
    default_setting VARCHAR(30)  NOT NULL         -- e.g. "3.3V", "1.8V", "1.8V/3.3V"
);

-- ---------------------------------------------------------------------------
-- configurations
--   One row per user pinmux project.  Multiple configurations can coexist
--   (e.g. different board variants).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS configurations (
    id           SERIAL PRIMARY KEY,
    name         VARCHAR(200) NOT NULL,
    board_name   VARCHAR(100),
    revision     INTEGER      NOT NULL DEFAULT 1,
    notes        TEXT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- pin_configs
--   Per-pin customer choices within a configuration.
--   Seeded from the tmpl_* fields in pins; updated by the user via the UI.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pin_configs (
    id               SERIAL PRIMARY KEY,
    config_id        INTEGER      NOT NULL REFERENCES configurations(id) ON DELETE CASCADE,
    pin_id           INTEGER      NOT NULL REFERENCES pins(id)           ON DELETE RESTRICT,

    -- Customer choices (mirrors the "Filled in by Customers" columns AS–BH)
    customer_usage   VARCHAR(100),
    pin_direction    VARCHAR(30),
    initial_state    VARCHAR(30),
    wake_pin         VARCHAR(10),
    lock             VARCHAR(10),
    e_io_od          VARCHAR(10),    -- E_IO_OD / Open-Drain Select
    drv_type         VARCHAR(10),    -- DRV_TYPE (LPDR)
    e_lpbk           VARCHAR(10),    -- E_LPBK Loopback Select
    e_18v            VARCHAR(10),    -- E_18V
    schmitt          VARCHAR(20),
    e_hsrx18v        VARCHAR(10),
    int_pull_up      VARCHAR(20),    -- internal pull-up resistor value
    int_pull_down    VARCHAR(20),
    ext_pull_up      VARCHAR(20),    -- external pull-up resistor value
    ext_pull_down    VARCHAR(20),
    deep_sleep_state VARCHAR(30),

    -- Pin electrical config (cols AH-AK; customer-editable, used by DTS generator)
    pupd             VARCHAR(20),    -- NORMAL / PULL_UP / PULL_DOWN
    tristate         VARCHAR(20),    -- NORMAL / TRISTATE
    e_input          VARCHAR(20),    -- ENABLE / DISABLE
    gpio_init        VARCHAR(10),    -- N/A / 0 / 1

    -- Computed validation results (updated server-side on every save)
    valid_customer_usage   BOOLEAN,
    valid_pin_direction    BOOLEAN,
    valid_initial_state    BOOLEAN,
    valid_wake             BOOLEAN,
    valid_resistor         BOOLEAN,
    valid_rcv_sel          BOOLEAN,
    is_valid               BOOLEAN  GENERATED ALWAYS AS (
        COALESCE(valid_customer_usage, TRUE)
        AND COALESCE(valid_pin_direction, TRUE)
        AND COALESCE(valid_initial_state, TRUE)
        AND COALESCE(valid_wake, TRUE)
        AND COALESCE(valid_resistor, TRUE)
        AND COALESCE(valid_rcv_sel, TRUE)
    ) STORED,

    UNIQUE (config_id, pin_id)
);

CREATE INDEX IF NOT EXISTS pin_configs_config_idx ON pin_configs(config_id);

-- ---------------------------------------------------------------------------
-- pad_voltage_configs
--   Per-configuration voltage rail overrides.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pad_voltage_configs (
    id              SERIAL PRIMARY KEY,
    config_id       INTEGER      NOT NULL REFERENCES configurations(id) ON DELETE CASCADE,
    rail_id         INTEGER      NOT NULL REFERENCES pad_voltage_rails(id) ON DELETE RESTRICT,
    voltage_setting VARCHAR(30)  NOT NULL,
    UNIQUE (config_id, rail_id)
);

COMMIT;
